#!/usr/bin/env python3
from __future__ import annotations

import argparse
import importlib.util
import os
import shlex
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from types import ModuleType


MENV_ROOT = Path(
    os.environ.get(
        "MENV_ROOT",
        Path.home() / ".menv",
    )
)
KYOPRO_ROOT = MENV_ROOT / "envs" / "kyopro"

sys.path.insert(0, str(MENV_ROOT / ".lib"))
sys.path.insert(0, str(KYOPRO_ROOT / ".lib"))

from common import info, ng, ok  # noqa: E402


UINT64_MAX = (1 << 64) - 1


@dataclass(frozen=True)
class LanguageHandler:
    module: ModuleType
    extensions: frozenset[str]


@dataclass(frozen=True)
class ExecutionResult:
    returncode: int | None
    stdout: bytes
    stderr: bytes
    timed_out: bool = False


def positive_int(value: str) -> int:
    number = int(value)

    if number <= 0:
        raise argparse.ArgumentTypeError(
            "must be greater than zero"
        )

    return number


def positive_float(value: str) -> float:
    number = float(value)

    if number <= 0:
        raise argparse.ArgumentTypeError(
            "must be greater than zero"
        )

    return number


def uint64(value: str) -> int:
    number = int(value)

    if not 0 <= number <= UINT64_MAX:
        raise argparse.ArgumentTypeError(
            f"must be between 0 and {UINT64_MAX}"
        )

    return number


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "compare a solution with a brute-force "
            "solution using rad"
        ),
    )
    parser.add_argument(
        "problem",
        help="problem name, for example: a",
    )
    parser.add_argument(
        "-n",
        "--count",
        type=positive_int,
        help=(
            "number of cases "
            "(default: run until a failure)"
        ),
    )
    parser.add_argument(
        "--seed",
        type=uint64,
        default=1,
        help="first rad seed (default: 1)",
    )
    parser.add_argument(
        "--batch-size",
        type=positive_int,
        default=100,
        help=(
            "cases generated by one rad invocation "
            "(default: 100)"
        ),
    )
    parser.add_argument(
        "--timeout",
        type=positive_float,
        default=2.0,
        help=(
            "timeout for each program in seconds "
            "(default: 2)"
        ),
    )
    parser.add_argument(
        "--rad-file",
        type=Path,
        help="generator file (default: <problem>.rad)",
    )
    parser.add_argument(
        "--no-build",
        action="store_true",
        help="reuse bundled sources in the build directory",
    )
    parser.add_argument(
        "--exact",
        action="store_true",
        help=(
            "compare output bytes exactly instead of "
            "comparing tokens"
        ),
    )

    return parser.parse_args()


def require_command(name: str) -> str:
    path = shutil.which(name)

    if path is None:
        ng(f"{name} not found")
        raise SystemExit(1)

    return path


def load_language_handlers(
    directory: Path,
) -> list[LanguageHandler]:
    if not directory.is_dir():
        ng(f"language directory not found: {directory}")
        raise SystemExit(1)

    handlers: list[LanguageHandler] = []
    owners: dict[str, Path] = {}

    for path in sorted(directory.glob("*.py")):
        if path.name.startswith("_"):
            continue

        module_name = f"kstre_language_{path.stem}"
        spec = importlib.util.spec_from_file_location(
            module_name,
            path,
        )

        if spec is None or spec.loader is None:
            ng(f"cannot load language handler: {path}")
            raise SystemExit(1)

        module = importlib.util.module_from_spec(spec)
        sys.modules[module_name] = module

        try:
            spec.loader.exec_module(module)
        except Exception:
            sys.modules.pop(module_name, None)
            raise

        extensions_value = getattr(
            module,
            "EXTENSIONS",
            None,
        )
        prepare = getattr(module, "prepare", None)

        if (
            not isinstance(
                extensions_value,
                (set, frozenset),
            )
            or not callable(prepare)
        ):
            ng(f"invalid language handler: {path}")
            info(
                "a handler must define "
                "EXTENSIONS and prepare()"
            )
            raise SystemExit(1)

        extensions = frozenset(extensions_value)

        if not extensions or any(
            not isinstance(extension, str)
            or not extension.startswith(".")
            for extension in extensions
        ):
            ng(f"invalid EXTENSIONS in: {path}")
            raise SystemExit(1)

        for extension in extensions:
            previous = owners.get(extension)

            if previous is not None:
                ng(
                    "duplicate language extension: "
                    f"{extension}"
                )
                info(
                    "handlers: "
                    f"{previous.name}, {path.name}"
                )
                raise SystemExit(1)

            owners[extension] = path

        handlers.append(
            LanguageHandler(
                module,
                extensions,
            )
        )

    if not handlers:
        ng(f"no language handlers found: {directory}")
        raise SystemExit(1)

    return handlers


def resolve_solution(
    root: Path,
    problem: str,
    handlers: list[LanguageHandler],
) -> tuple[Path, LanguageHandler]:
    problem_path = Path(problem)

    if (
        problem_path.name != problem
        or problem in {".", ".."}
    ):
        ng("problem must be a name, not a path")
        raise SystemExit(1)

    bases = [
        root / problem,
        root / problem / "main",
        root / problem / problem,
    ]

    found: list[
        tuple[Path, LanguageHandler]
    ] = []

    for handler in handlers:
        for extension in sorted(handler.extensions):
            for base in bases:
                source = base.with_suffix(extension)

                if source.is_file():
                    found.append((source, handler))

    if not found:
        ng(f"solution source not found: {problem}")
        raise SystemExit(1)

    if len(found) != 1:
        ng(f"multiple solution sources found: {problem}")

        for source, _ in found:
            info(str(source.relative_to(root)))

        raise SystemExit(1)

    return found[0]


def resolve_brute(solution: Path) -> Path:
    brute = solution.with_name(
        f"{solution.stem}.brute{solution.suffix}"
    )

    if not brute.is_file():
        ng(
            "brute-force source not found: "
            f"{brute.name}"
        )
        raise SystemExit(1)

    return brute


def resolve_rad_file(
    root: Path,
    problem: str,
    value: Path | None,
) -> Path:
    path = (
        value
        if value is not None
        else root / f"{problem}.rad"
    )

    if not path.is_absolute():
        path = root / path

    path = path.resolve()

    if not path.is_file():
        ng(f"rad file not found: {path}")
        raise SystemExit(1)

    return path


def check_rad(
    rad: str,
    rad_file: Path,
    root: Path,
) -> None:
    info(f"checking generator: {rad_file.name}")

    result = subprocess.run(
        [
            rad,
            "check",
            str(rad_file),
        ],
        cwd=root,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )

    if result.returncode != 0:
        ng("generator check failed")

        if result.stdout:
            print()
            print(result.stdout, end="")

        raise SystemExit(result.returncode)

    ok(f"checked: {rad_file.name}")


def prepare_programs(
    handler: LanguageHandler,
    solution: Path,
    brute: Path,
    build_dir: Path,
    *,
    no_build: bool,
) -> tuple[list[str], list[str]]:
    prepare = handler.module.prepare

    solution_command, _ = prepare(
        solution,
        build_dir,
        no_build=no_build,
        output_name=f"sol{solution.suffix}",
    )

    brute_command, _ = prepare(
        brute,
        build_dir,
        no_build=no_build,
        output_name=f"brute{brute.suffix}",
    )

    return solution_command, brute_command


def generate_cases(
    rad: str,
    rad_file: Path,
    root: Path,
    *,
    seed: int,
    count: int,
) -> list[bytes]:
    result = subprocess.run(
        [
            rad,
            "generate",
            str(rad_file),
            "--seed",
            str(seed),
            "--count",
            str(count),
            "--format",
            "nul",
        ],
        cwd=root,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )

    if result.returncode != 0:
        ng(f"generation failed: seed={seed}")

        if result.stderr:
            print()
            print(
                result.stderr.decode(
                    errors="replace"
                ),
                end="",
            )

        raise SystemExit(result.returncode)

    cases = result.stdout.split(b"\0")

    if len(cases) != count:
        ng(
            "rad returned an invalid "
            "NUL-separated batch"
        )
        info(f"expected: {count} cases")
        info(f"actual: {len(cases)} cases")
        raise SystemExit(1)

    return cases


def execute(
    command: list[str],
    input_data: bytes,
    root: Path,
    *,
    timeout: float,
) -> ExecutionResult:
    try:
        result = subprocess.run(
            command,
            cwd=root,
            input=input_data,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=timeout,
        )
    except subprocess.TimeoutExpired as error:
        return ExecutionResult(
            returncode=None,
            stdout=error.stdout or b"",
            stderr=error.stderr or b"",
            timed_out=True,
        )

    return ExecutionResult(
        returncode=result.returncode,
        stdout=result.stdout,
        stderr=result.stderr,
    )


def failure_reason(
    solution: ExecutionResult,
    brute: ExecutionResult,
    *,
    exact: bool,
) -> str | None:
    if solution.timed_out:
        return "solution timed out"

    if brute.timed_out:
        return "brute-force solution timed out"

    if solution.returncode != 0:
        return (
            "solution runtime error "
            f"(exit code: {solution.returncode})"
        )

    if brute.returncode != 0:
        return (
            "brute-force solution runtime error "
            f"(exit code: {brute.returncode})"
        )

    solution_output = (
        solution.stdout
        if exact
        else solution.stdout.split()
    )
    brute_output = (
        brute.stdout
        if exact
        else brute.stdout.split()
    )

    if solution_output != brute_output:
        return "answer mismatch"

    return None


def write_failure_files(
    build_dir: Path,
    input_data: bytes,
    solution: ExecutionResult,
    brute: ExecutionResult,
) -> None:
    build_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    (build_dir / "failed.in").write_bytes(
        input_data
    )
    (build_dir / "failed.sol.out").write_bytes(
        solution.stdout
    )
    (build_dir / "failed.sol.err").write_bytes(
        solution.stderr
    )
    (build_dir / "failed.brute.out").write_bytes(
        brute.stdout
    )
    (build_dir / "failed.brute.err").write_bytes(
        brute.stderr
    )


def print_data(
    title: str,
    data: bytes,
) -> None:
    print()
    print(f"{title}:")

    if not data:
        print("<empty>")
        return

    text = data.decode(errors="replace")
    print(text, end="")

    if not text.endswith("\n"):
        print()


def report_failure(
    reason: str,
    seed: int,
    input_data: bytes,
    solution: ExecutionResult,
    brute: ExecutionResult,
    build_dir: Path,
    rad: str,
    rad_file: Path,
) -> None:
    write_failure_files(
        build_dir,
        input_data,
        solution,
        brute,
    )

    ng(reason)
    info(f"seed: {seed}")
    info(
        f"input saved: "
        f"{build_dir / 'failed.in'}"
    )
    info(
        "reproduce: "
        + shlex.join(
            [
                rad,
                "generate",
                str(rad_file),
                "--seed",
                str(seed),
            ]
        )
    )

    print_data("input", input_data)
    print_data("solution", solution.stdout)

    if solution.stderr:
        print_data(
            "solution stderr",
            solution.stderr,
        )

    print_data("brute", brute.stdout)

    if brute.stderr:
        print_data(
            "brute stderr",
            brute.stderr,
        )


def stress_test(
    solution_command: list[str],
    brute_command: list[str],
    rad: str,
    rad_file: Path,
    root: Path,
    build_dir: Path,
    *,
    first_seed: int,
    total_count: int | None,
    batch_size: int,
    timeout: float,
    exact: bool,
) -> int:
    tested = 0
    seed = first_seed

    while (
        total_count is None
        or tested < total_count
    ):
        remaining = (
            None
            if total_count is None
            else total_count - tested
        )
        count = (
            batch_size
            if remaining is None
            else min(batch_size, remaining)
        )

        if seed > UINT64_MAX - (count - 1):
            ng("seed range exceeds uint64")
            return 1

        cases = generate_cases(
            rad,
            rad_file,
            root,
            seed=seed,
            count=count,
        )

        for offset, input_data in enumerate(cases):
            case_seed = seed + offset

            solution = execute(
                solution_command,
                input_data,
                root,
                timeout=timeout,
            )
            brute = execute(
                brute_command,
                input_data,
                root,
                timeout=timeout,
            )

            reason = failure_reason(
                solution,
                brute,
                exact=exact,
            )

            if reason is not None:
                report_failure(
                    reason,
                    case_seed,
                    input_data,
                    solution,
                    brute,
                    build_dir,
                    rad,
                    rad_file,
                )
                return 1

            tested += 1

        seed += count

        info(
            f"passed: {tested} cases "
            f"(last seed: {seed - 1})"
        )

    ok(f"all tests passed ({tested}/{tested})")
    return 0


def main() -> int:
    args = parse_args()

    root = Path.cwd().resolve()
    script_dir = Path(__file__).resolve().parent

    handlers = load_language_handlers(
        script_dir / "ktest_languages"
    )

    solution, handler = resolve_solution(
        root,
        args.problem,
        handlers,
    )
    brute = resolve_brute(solution)
    rad_file = resolve_rad_file(
        root,
        args.problem,
        args.rad_file,
    )
    rad = require_command("rad")
    build_dir = (
        root
        / ".build"
        / args.problem
    )

    check_rad(
        rad,
        rad_file,
        root,
    )

    (
        solution_command,
        brute_command,
    ) = prepare_programs(
        handler,
        solution,
        brute,
        build_dir,
        no_build=args.no_build,
    )

    info(
        f"stress testing: "
        f"{solution.name} <-> {brute.name} "
        f"(seed: {args.seed})"
    )

    try:
        return stress_test(
            solution_command,
            brute_command,
            rad,
            rad_file,
            root,
            build_dir,
            first_seed=args.seed,
            total_count=args.count,
            batch_size=args.batch_size,
            timeout=args.timeout,
            exact=args.exact,
        )
    except KeyboardInterrupt:
        print()
        info("interrupted")
        return 130


if __name__ == "__main__":
    raise SystemExit(main())